In [18]:
import numpy as np

print("Problem 1: Array Creation")

empty_array = np.empty((2, 2))
print("1. Empty array (2x2):\n", empty_array)

ones_array = np.ones((4, 2))
print("2. All ones array (4x2):\n", ones_array)

full_array = np.full((3, 3), 7)
print("3. Full array (3x3) with 7:\n", full_array)

ref_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(ref_array)
print("4. Zeros like ref_array:\n", zeros_like_array)

ones_like_array = np.ones_like(ref_array)
print("5. Ones like ref_array:\n", ones_like_array)

new_list = [1, 2, 3, 4]
converted_array = np.array(new_list)
print("6. Converted list to array:\n", converted_array)


Problem 1: Array Creation
1. Empty array (2x2):
 [[2.5e-323 1.5e-323]
 [9.9e-324 4.9e-324]]
2. All ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
3. Full array (3x3) with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
4. Zeros like ref_array:
 [[0 0]
 [0 0]]
5. Ones like ref_array:
 [[1 1]
 [1 1]]
6. Converted list to array:
 [1 2 3 4]


In [19]:
# Problem 2:
print("\nProblem 2: Array Manipulation")
range_array = np.arange(10, 50)
print("1. Array from 10 to 49:\n", range_array)
matrix_3x3 = np.arange(9).reshape(3, 3)
print("2. 3x3 matrix from 0 to 8:\n", matrix_3x3)
identity_matrix = np.eye(3)
print("3. Identity matrix (3x3):\n", identity_matrix)
random_array = np.random.random(30)
print("4. Random array (size 30):\n", random_array)
print("Mean of array:", random_array.mean())
rand_10x10 = np.random.random((10, 10))
print("5. Random 10x10 array:\n", rand_10x10)
print("Min:", rand_10x10.min(), "Max:", rand_10x10.max())
zero_array = np.zeros(10)
zero_array[4] = 1
print("6. Zero array with 5th element = 1:\n", zero_array)
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]
print("7. Reversed array:\n", reversed_arr)
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("8. 2D array with 1 on border and 0 inside:\n", border_array)
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("9. 8x8 checkerboard pattern:\n", checkerboard)


Problem 2: Array Manipulation
1. Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
2. 3x3 matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3. Identity matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4. Random array (size 30):
 [0.26143264 0.37414919 0.28403579 0.98896243 0.81537497 0.57485355
 0.17155103 0.46464771 0.50093071 0.60639015 0.60202635 0.79516521
 0.20043409 0.85479629 0.83560969 0.073964   0.90757913 0.88649434
 0.30337049 0.640167   0.17289244 0.77021465 0.50821354 0.18054954
 0.10841842 0.51365624 0.2503808  0.89720993 0.17102178 0.53608359]
Mean of array: 0.5083525228924983
5. Random 10x10 array:
 [[0.41414259 0.37968643 0.57799274 0.5939736  0.43969467 0.73054279
  0.1986308  0.93063442 0.45350796 0.38915608]
 [0.32841124 0.60341673 0.0729663  0.54658411 0.30051515 0.6815966
  0.6217933  0.06640462 0.93242504 0.82344994]
 [0.08970277 0.95890203 0.8028182  0.76512042 0.65

In [20]:
import numpy as np

print("\nProblem 3: Array Operations")

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("x:", x)
print("y:", y)
print("v:", v)
print("w:", w)

print("1. x + y:", x + y)
print("2. x - y:", x - y)
print("3. x * 3:", x * 3)
print("4. Square of x:", x ** 2)

print("5. Dot products:")
print("v . w =", np.dot(v, w))
print("x . v =\n", np.dot(x, v))
print("x . y =\n", np.dot(x, y))

print("6. Concatenate x and y along rows:\n", np.concatenate((x, y), axis=0))
print("Concatenate v and w along columns:\n", np.vstack((v, w)))

print("7. Concatenate x and v:")
try:
    result = np.concatenate((x, v), axis=0)
    print(result)
except ValueError as e:
    print("Error:", e)



Problem 3: Array Operations
x: [[1 2]
 [3 5]]
y: [[5 6]
 [7 8]]
v: [ 9 10]
w: [11 12]
1. x + y: [[ 6  8]
 [10 13]]
2. x - y: [[-4 -4]
 [-4 -3]]
3. x * 3: [[ 3  6]
 [ 9 15]]
4. Square of x: [[ 1  4]
 [ 9 25]]
5. Dot products:
v . w = 219
x . v =
 [29 77]
x . y =
 [[19 22]
 [50 58]]
6. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]
7. Concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [21]:
import numpy as np

print("Problem 4: Matrix Operations")

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("1. A * A_inv:", identity_check)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("2. AB:", AB)
print("BA:", BA)
print("AB == BA?", np.allclose(AB, BA))

AB_T = AB.T
BT_AT = np.dot(B.T, A.T)
print("3. (AB)^T:", AB_T)
print("B^T * A^T:", BT_AT)
print("(AB)^T == B^T * A^T?", np.allclose(AB_T, BT_AT))


Problem 4: Matrix Operations
1. A * A_inv: [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
2. AB: [[23 13]
 [51 29]]
BA: [[36 44]
 [13 16]]
AB == BA? False
3. (AB)^T: [[23 51]
 [13 29]]
B^T * A^T: [[23 51]
 [13 29]]
(AB)^T == B^T * A^T? True


In [22]:
import numpy as np

print("Solving Linear Equations")

A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])
B_sys = np.array([-1, -3, 9])

A_inv_sys = np.linalg.inv(A_sys)
X = np.dot(A_inv_sys, B_sys)

print("Solution [x, y, z]:", X)


Solving Linear Equations
Solution [x, y, z]: [ 2.  1. -2.]


In [23]:
import time

size = 1_000_000
matrix_size = 1000

print("Experiment: How Fast is NumPy?")


Experiment: How Fast is NumPy?


In [24]:
print("1. Element-wise Addition")
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
list_add = [a + b for a, b in zip(list1, list2)]
end = time.time()
print("Python List Addition Time:", end - start, "seconds")

arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
np_add = arr1 + arr2
end = time.time()
print("NumPy Array Addition Time:", end - start, "seconds")

1. Element-wise Addition
Python List Addition Time: 0.10100531578063965 seconds
NumPy Array Addition Time: 0.002953052520751953 seconds


In [25]:
print("2. Element-wise Multiplication")
start = time.time()
list_mul = [a * b for a, b in zip(list1, list2)]
end = time.time()
print("Python List Multiplication Time:", end - start, "seconds")

start = time.time()
np_mul = arr1 * arr2
end = time.time()
print("NumPy Array Multiplication Time:", end - start, "seconds")

2. Element-wise Multiplication
Python List Multiplication Time: 0.1112222671508789 seconds
NumPy Array Multiplication Time: 0.004202365875244141 seconds


In [26]:
print("3. Dot Product")
start = time.time()
list_dot = sum(a * b for a, b in zip(list1, list2))
end = time.time()
print("Python List Dot Product Time:", end - start, "seconds")

start = time.time()
np_dot = np.dot(arr1, arr2)
end = time.time()
print("NumPy Array Dot Product Time:", end - start, "seconds")

3. Dot Product
Python List Dot Product Time: 0.09410929679870605 seconds
NumPy Array Dot Product Time: 0.0024652481079101562 seconds


In [27]:
import time
import numpy as np

# Sizes
size = 1_000_000         # For element-wise operations
matrix_size = 1000       # For matrix multiplication

print("Experiment: How Fast is NumPy?\n")

# 1. Element-wise Addition
print("1. Element-wise Addition")
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
np_add = arr1 + arr2
end = time.time()
print("NumPy Array Addition Time:", end - start, "seconds\n")

# 2. Element-wise Multiplication
print("2. Element-wise Multiplication")
start = time.time()
np_mul = arr1 * arr2
end = time.time()
print("NumPy Array Multiplication Time:", end - start, "seconds\n")

# 3. Dot Product
print("3. Dot Product")
start = time.time()
np_dot = np.dot(arr1, arr2)
end = time.time()
print("NumPy Array Dot Product Time:", end - start, "seconds\n")

# 4. Matrix Multiplication
print("4. Matrix Multiplication")
np_matrix1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
np_matrix2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

start = time.time()
np_result_matrix = np.dot(np_matrix1, np_matrix2)
end = time.time()
print("NumPy Matrix Multiplication Time:", end - start, "seconds")


Experiment: How Fast is NumPy?

1. Element-wise Addition
NumPy Array Addition Time: 0.003609180450439453 seconds

2. Element-wise Multiplication
NumPy Array Multiplication Time: 0.0029222965240478516 seconds

3. Dot Product
NumPy Array Dot Product Time: 0.002206563949584961 seconds

4. Matrix Multiplication
NumPy Matrix Multiplication Time: 2.3309781551361084 seconds
